import { test, expect } from '@playwright/test';

test('CPCN001', async ({ page }) => {
    test.setTimeout(120000);

    await page.goto('https://francocardenas.me/wp-login.php?redirect_to=https%3A%2F%2Ffrancocardenas.me%2Fwp-admin%2F&reauth=1');
    await page.getByLabel('Username or Email Address').click();
    await page.getByLabel('Username or Email Address').fill('user');
    await page.getByLabel('Password', { exact: true }).click();
    await page.getByLabel('Password', { exact: true }).fill(':Y@8SmnRZuBK');
    await page.getByRole('button', { name: 'Log In' }).click();
    await page.locator('#menu-posts-product').getByRole('link', { name: 'Products', exact: true }).click();
    await page.getByLabel('Main menu', { exact: true }).getByRole('link', { name: 'Add New', exact: true }).click();
    await page.getByLabel('Product name').click();
    await page.getByLabel('Product name').fill('Casaca');
    await page.frameLocator('#content_ifr').getByRole('paragraph').click();
    await page.frameLocator('#content_ifr').locator('#tinymce').fill('Hermosa casaca hecha de telas finas, de buena calidad, fácil de lavar y duradera');
    await page.getByLabel('Virtual:').check();
    await page.getByLabel('Downloadable:').check();
    await page.getByLabel('Regular price (S/)').click();
    await page.getByLabel('Regular price (S/)').fill('75.00');
    await page.getByLabel('Sale price (S/)').click();
    await page.getByLabel('Sale price (S/)').fill('65.00');
    await page.getByRole('link', { name: 'Schedule', exact: true }).click();
    await page.getByPlaceholder('From… YYYY-MM-DD').click();
    await page.getByPlaceholder('From… YYYY-MM-DD').fill('2024-07-08');
    await page.getByRole('button', { name: 'Close' }).click();
    await page.getByPlaceholder('To…  YYYY-MM-DD').click();
    await page.getByPlaceholder('To…  YYYY-MM-DD').fill('2024-08-31');
    await page.getByRole('button', { name: 'Close' }).click();
    await page.getByRole('link', { name: 'Add File' }).click();
    await page.getByPlaceholder('File name').click();
    await page.getByPlaceholder('File name').fill('content');
    await page.getByRole('link', { name: 'Choose file' }).click();
    await page.getByLabel('book', { exact: true }).click();
    await page.getByRole('button', { name: 'Insert file URL' }).click();
    await page.getByPlaceholder('Unlimited').click();
    await page.getByPlaceholder('Unlimited').fill('10');
    await page.getByPlaceholder('Never').click();
    await page.getByPlaceholder('Never').fill('12');
    await page.getByRole('link', { name: 'Inventory' }).click();
    await page.getByLabel('SKU', { exact: true }).click();
    await page.getByLabel('SKU', { exact: true }).fill('CAS-ALT-FIN-1');
    await page.getByLabel('Stock management').check();
    await page.getByLabel('Quantity', { exact: true }).click();
    await page.getByLabel('Quantity', { exact: true }).fill('50');
    await page.getByPlaceholder('Store-wide threshold (2)').click();
    await page.getByPlaceholder('Store-wide threshold (2)').fill('10');
    await page.getByLabel('Sold individually').check();
    await page.getByRole('link', { name: 'Linked Products' }).click();
    await page.locator('p').filter({ hasText: 'Upsells' }).getByPlaceholder('Search for a product…').click();
    await page.locator('p').filter({ hasText: 'Upsells' }).getByPlaceholder('Search for a product…').press('CapsLock');
    await page.locator('p').filter({ hasText: 'Upsells' }).getByPlaceholder('Search for a product…').fill('P');
    await page.locator('p').filter({ hasText: 'Upsells' }).getByPlaceholder('Search for a product…').press('CapsLock');
    await page.locator('p').filter({ hasText: 'Upsells' }).getByPlaceholder('Search for a product…').fill('Polo');
    await page.getByRole('option', { name: 'Polo (woo-polo)' }).click();
    await page.getByRole('textbox', { name: 'Search for a product…' }).click();
    await page.getByRole('textbox', { name: 'Search for a product…' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Search for a product…' }).fill('P');
    await page.getByRole('textbox', { name: 'Search for a product…' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Search for a product…' }).fill('Polo');
    await page.getByRole('option', { name: 'Polo (woo-polo)' }).click();
    await page.getByRole('link', { name: 'Attributes' }).click();
    await page.getByText('Add existing').click();
    await page.getByRole('option', { name: 'Color' }).click();
    await page.getByRole('link', { name: 'Advanced' }).click();
    await page.getByLabel('Purchase note').click();
    await page.getByLabel('Purchase note').fill('No hay reembolso, solo se cambiará el producto a uno nuevo');
    await page.getByLabel('Menu order').click();
    await page.getByLabel('Menu order').fill('5');
    await page.getByRole('link', { name: 'Get more options' }).click();
    await page.getByRole('link', { name: 'Pinterest' }).click();
    await page.getByLabel('Condition', { exact: true }).selectOption('new');
    await page.getByText('Search for a category…').click();
    await page.getByRole('combobox').nth(4).fill('Clo');
    await page.getByRole('option', { name: 'Apparel & Accessories > Clothing', exact: true }).click();
    await page.frameLocator('#excerpt_ifr').getByRole('paragraph').click();
    await page.frameLocator('#excerpt_ifr').locator('#tinymce').fill('Casaca de tela fina,buena calidad, duradera, fácil lavado');
    await page.getByRole('link', { name: 'Set product image' }).click();
    await page.getByRole('checkbox', { name: 'hoodie-with-logo-2.jpg' }).click();
    await page.getByRole('button', { name: 'Set product image' }).click();
    await page.getByRole('link', { name: 'Add product gallery images' }).click();
    await page.getByRole('checkbox', { name: 'hoodie-2.jpg' }).click();
    await page.getByRole('button', { name: 'Add to gallery' }).click();
    await page.getByRole('link', { name: 'Add product gallery images' }).click();
    await page.getByRole('checkbox', { name: 'hoodie-with-pocket-2.jpg' }).click();
    await page.getByRole('button', { name: 'Add to gallery' }).click();
    await page.getByRole('link', { name: 'Add product gallery images' }).click();
    await page.getByRole('checkbox', { name: 'hoodie-green-1.jpg' }).click();
    await page.getByRole('button', { name: 'Add to gallery' }).click();
    await page.getByRole('checkbox', { name: 'Clothing' }).check();
    await page.getByLabel('Add new tag').click();
    await page.getByLabel('Add new tag').fill('Alta Calidad');
    await page.getByRole('option', { name: 'Alta Calidad' }).click();
    await page.getByRole('button', { name: 'Add', exact: true }).click();
    await page.getByRole('link', { name: 'Edit', exact: true }).click();
    await page.getByLabel('This is a featured product').check();
    await page.getByRole('link', { name: 'OK' }).click();
    await page.getByRole('button', { name: 'Publish', exact: true }).click();
    await page.getByRole('link', { name: 'https://francocardenas.me/' }).click();

    await expect(page.getByRole('heading', { level: 1, name: 'Casaca' })).toBeVisible();

    //? Delete Last Added From Dashboard
    await page.goto(`https://francocardenas.me/wp-admin/edit.php?post_type=product`);
    await page.waitForTimeout(3000);
    await page.locator("//html/body/div[1]/div[2]/div[3]/div[1]/div[6]/form[1]/table/tbody/tr[1]/th/input").click();
    await page.locator("select[name='action']").selectOption("trash");
    await page.locator("input[id='doaction']").click();
    await page.waitForTimeout(3000);
});
